In [2]:
import pandas as pd

# Time Features

In [16]:
date_features = pd.read_parquet("../data/02_intermediate/transactions_train.parquet", columns=["t_dat"])
time_features = pd.read_parquet("../data/04_feature/transactions_train_time_ft.parquet")

In [4]:
date_features["t_dat"] = pd.to_datetime(date_features["t_dat"])

In [15]:
days, _ = pd.factorize(date_features["t_dat"])
days += 1
days

array([  1,   1,   1, ..., 734, 734, 734], dtype=int64)

In [14]:
weeks = (days // 7) + 1
weeks

array([  1,   1,   1, ..., 105, 105, 105], dtype=int64)

In [16]:
from sklearn.preprocessing import FunctionTransformer

def sin_transformer(period):
	return FunctionTransformer(lambda x: np.sin(x / period * 2 * np.pi))

In [17]:
sin_transformer(365).fit_transform(days)

array([0.        , 0.        , 0.        , ..., 0.05161967, 0.05161967,
       0.05161967])

In [17]:
time_features

day  week   day_sin   day_cos
0           1     1  0.017213  0.999852
1           1     1  0.017213  0.999852
2           1     1  0.017213  0.999852
3           1     1  0.017213  0.999852
4           1     1  0.017213  0.999852
...       ...   ...       ...       ...
31788319  734   105  0.068802  0.997630
31788320  734   105  0.068802  0.997630
31788321  734   105  0.068802  0.997630
31788322  734   105  0.068802  0.997630
31788323  734   105  0.068802  0.997630

[31788324 rows x 4 columns]